spring:
  application:
    name: cours-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_cours
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 6006
